// Generated by pixel_foundry_proc/emit.py - rules, not pixels.
// sp: source pixels on the 128x96 design grid (origin top-left). light: unit vector.
const vec3 pfCitadel_pal[14] = vec3[14](
    vec3(0,0,0)/255.0,
    vec3(13,17,26)/255.0,
    vec3(23,29,40)/255.0,
    vec3(35,44,56)/255.0,
    vec3(49,61,72)/255.0,
    vec3(69,80,87)/255.0,
    vec3(99,108,109)/255.0,
    vec3(143,153,148)/255.0,
    vec3(33,38,55)/255.0,
    vec3(52,56,74)/255.0,
    vec3(112,101,72)/255.0,
    vec3(177,157,105)/255.0,
    vec3(45,76,80)/255.0,
    vec3(103,151,143)/255.0);
bool pfCitadel_cross(vec2 p, vec2 a, vec2 b) {
    return ((a.y > p.y) != (b.y > p.y)) &&
           (p.x < (b.x - a.x) * (p.y - a.y) / (b.y - a.y == 0.0 ? 1e-6 : (b.y - a.y)) + a.x);
}

bool pfCitadel_seg(vec2 p, vec2 a, vec2 b, float w) {
    vec2 pa = p - a, ba = b - a;
    float h = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-6), 0.0, 1.0);
    return length(pa - ba * h) <= w;
}

bool pfCitadel_oct(vec2 p, vec2 c, vec2 h, float bevel) {
    vec2 q = abs(p - c) - (h - bevel);
    return (length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0)) - bevel <= 0.0;
}
vec3 pfCitadel(vec2 sp, vec2 light) {
    vec3 o = vec3(0.0);
    vec2 p = sp;
    float lit = clamp(0.5 + 0.5 * dot(normalize(light + vec2(1e-4, 1e-4)), vec2(0.7071, 0.7071)), 0.0, 1.0);
    if((p.x>=19.5 && p.x<=108.5 && p.y>=47.5 && p.y<=55.5)) o = pfCitadel_pal[2];
    if((p.x>=19.5 && p.x<=108.5 && p.y>=47.5 && p.y<=49.5)) o = pfCitadel_pal[5];
    if(pfCitadel_seg(p, vec2(24,50), vec2(28,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(32,50), vec2(36,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(40,50), vec2(44,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(48,50), vec2(52,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(56,50), vec2(60,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(64,50), vec2(68,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(72,50), vec2(76,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(80,50), vec2(84,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(88,50), vec2(92,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(96,50), vec2(100,54), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(104,50), vec2(108,54), 0.5)) o = pfCitadel_pal[4];
    if((((((((pfCitadel_cross(p,vec2(52,29),vec2(71,29))!=pfCitadel_cross(p,vec2(71,29),vec2(75,33)))!=pfCitadel_cross(p,vec2(75,33),vec2(75,72)))!=pfCitadel_cross(p,vec2(75,72),vec2(71,76)))!=pfCitadel_cross(p,vec2(71,76),vec2(52,76)))!=pfCitadel_cross(p,vec2(52,76),vec2(48,72)))!=pfCitadel_cross(p,vec2(48,72),vec2(48,33)))!=pfCitadel_cross(p,vec2(48,33),vec2(52,29)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(52,29),vec2(71,29))!=pfCitadel_cross(p,vec2(71,29),vec2(73,33)))!=pfCitadel_cross(p,vec2(73,33),vec2(73,73)))!=pfCitadel_cross(p,vec2(73,73),vec2(50,73)))!=pfCitadel_cross(p,vec2(50,73),vec2(48,33)))!=pfCitadel_cross(p,vec2(48,33),vec2(52,29)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(48,33), vec2(71,29), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(51,74), vec2(74,72), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(53,29), vec2(58,29), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(44,38),vec2(52,38))!=pfCitadel_cross(p,vec2(52,38),vec2(54,40)))!=pfCitadel_cross(p,vec2(54,40),vec2(54,65)))!=pfCitadel_cross(p,vec2(54,65),vec2(52,67)))!=pfCitadel_cross(p,vec2(52,67),vec2(44,67)))!=pfCitadel_cross(p,vec2(44,67),vec2(42,65)))!=pfCitadel_cross(p,vec2(42,65),vec2(42,40)))!=pfCitadel_cross(p,vec2(42,40),vec2(44,38)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(44,38),vec2(52,38))!=pfCitadel_cross(p,vec2(52,38),vec2(52,40)))!=pfCitadel_cross(p,vec2(52,40),vec2(52,64)))!=pfCitadel_cross(p,vec2(52,64),vec2(44,64)))!=pfCitadel_cross(p,vec2(44,64),vec2(42,40)))!=pfCitadel_cross(p,vec2(42,40),vec2(44,38)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(42,40), vec2(52,38), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(45,65), vec2(53,65), 0.5)) o = pfCitadel_pal[1];
    if((p.x>=44.5 && p.x<=51.5 && p.y>=40.5 && p.y<=64.5)) o = pfCitadel_pal[1];
    if((p.x>=45.5 && p.x<=50.5 && p.y>=41.5 && p.y<=42.5)) o = pfCitadel_pal[8];
    if((p.x>=45.5 && p.x<=49.5 && p.y>=42.5 && p.y<=43.5)) o = pfCitadel_pal[9];
    if((p.x>=45.5 && p.x<=50.5 && p.y>=45.5 && p.y<=46.5)) o = pfCitadel_pal[8];
    if((p.x>=45.5 && p.x<=49.5 && p.y>=46.5 && p.y<=47.5)) o = pfCitadel_pal[9];
    if((p.x>=45.5 && p.x<=50.5 && p.y>=49.5 && p.y<=50.5)) o = pfCitadel_pal[8];
    if((p.x>=45.5 && p.x<=49.5 && p.y>=50.5 && p.y<=51.5)) o = pfCitadel_pal[9];
    if((p.x>=45.5 && p.x<=50.5 && p.y>=53.5 && p.y<=54.5)) o = pfCitadel_pal[8];
    if((p.x>=45.5 && p.x<=49.5 && p.y>=54.5 && p.y<=55.5)) o = pfCitadel_pal[9];
    if((p.x>=45.5 && p.x<=50.5 && p.y>=57.5 && p.y<=58.5)) o = pfCitadel_pal[8];
    if((p.x>=45.5 && p.x<=49.5 && p.y>=58.5 && p.y<=59.5)) o = pfCitadel_pal[9];
    if((p.x>=45.5 && p.x<=50.5 && p.y>=61.5 && p.y<=62.5)) o = pfCitadel_pal[8];
    if((p.x>=45.5 && p.x<=49.5 && p.y>=62.5 && p.y<=63.5)) o = pfCitadel_pal[9];
    if((p.x>=56.5 && p.x<=65.5 && p.y>=33.5 && p.y<=71.5)) o = pfCitadel_pal[2];
    if((((((((pfCitadel_cross(p,vec2(59,36),vec2(64,36))!=pfCitadel_cross(p,vec2(64,36),vec2(65,37)))!=pfCitadel_cross(p,vec2(65,37),vec2(65,43)))!=pfCitadel_cross(p,vec2(65,43),vec2(64,44)))!=pfCitadel_cross(p,vec2(64,44),vec2(59,44)))!=pfCitadel_cross(p,vec2(59,44),vec2(58,43)))!=pfCitadel_cross(p,vec2(58,43),vec2(58,37)))!=pfCitadel_cross(p,vec2(58,37),vec2(59,36)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(59,36),vec2(64,36))!=pfCitadel_cross(p,vec2(64,36),vec2(63,37)))!=pfCitadel_cross(p,vec2(63,37),vec2(63,41)))!=pfCitadel_cross(p,vec2(63,41),vec2(60,41)))!=pfCitadel_cross(p,vec2(60,41),vec2(58,37)))!=pfCitadel_cross(p,vec2(58,37),vec2(59,36)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(58,37), vec2(64,36), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(61,42), vec2(64,43), 0.5)) o = pfCitadel_pal[1];
    if((((((((pfCitadel_cross(p,vec2(59,48),vec2(64,48))!=pfCitadel_cross(p,vec2(64,48),vec2(65,49)))!=pfCitadel_cross(p,vec2(65,49),vec2(65,55)))!=pfCitadel_cross(p,vec2(65,55),vec2(64,56)))!=pfCitadel_cross(p,vec2(64,56),vec2(59,56)))!=pfCitadel_cross(p,vec2(59,56),vec2(58,55)))!=pfCitadel_cross(p,vec2(58,55),vec2(58,49)))!=pfCitadel_cross(p,vec2(58,49),vec2(59,48)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(59,48),vec2(64,48))!=pfCitadel_cross(p,vec2(64,48),vec2(63,49)))!=pfCitadel_cross(p,vec2(63,49),vec2(63,53)))!=pfCitadel_cross(p,vec2(63,53),vec2(60,53)))!=pfCitadel_cross(p,vec2(60,53),vec2(58,49)))!=pfCitadel_cross(p,vec2(58,49),vec2(59,48)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(58,49), vec2(64,48), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(61,54), vec2(64,55), 0.5)) o = pfCitadel_pal[1];
    if((((((((pfCitadel_cross(p,vec2(59,60),vec2(64,60))!=pfCitadel_cross(p,vec2(64,60),vec2(65,61)))!=pfCitadel_cross(p,vec2(65,61),vec2(65,67)))!=pfCitadel_cross(p,vec2(65,67),vec2(64,68)))!=pfCitadel_cross(p,vec2(64,68),vec2(59,68)))!=pfCitadel_cross(p,vec2(59,68),vec2(58,67)))!=pfCitadel_cross(p,vec2(58,67),vec2(58,61)))!=pfCitadel_cross(p,vec2(58,61),vec2(59,60)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(59,60),vec2(64,60))!=pfCitadel_cross(p,vec2(64,60),vec2(63,61)))!=pfCitadel_cross(p,vec2(63,61),vec2(63,65)))!=pfCitadel_cross(p,vec2(63,65),vec2(60,65)))!=pfCitadel_cross(p,vec2(60,65),vec2(58,61)))!=pfCitadel_cross(p,vec2(58,61),vec2(59,60)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(58,61), vec2(64,60), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(61,66), vec2(64,67), 0.5)) o = pfCitadel_pal[1];
    if((((((((pfCitadel_cross(p,vec2(16,24),vec2(24,24))!=pfCitadel_cross(p,vec2(24,24),vec2(27,27)))!=pfCitadel_cross(p,vec2(27,27),vec2(27,75)))!=pfCitadel_cross(p,vec2(27,75),vec2(24,78)))!=pfCitadel_cross(p,vec2(24,78),vec2(16,78)))!=pfCitadel_cross(p,vec2(16,78),vec2(13,75)))!=pfCitadel_cross(p,vec2(13,75),vec2(13,27)))!=pfCitadel_cross(p,vec2(13,27),vec2(16,24)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(16,24),vec2(24,24))!=pfCitadel_cross(p,vec2(24,24),vec2(25,27)))!=pfCitadel_cross(p,vec2(25,27),vec2(25,75)))!=pfCitadel_cross(p,vec2(25,75),vec2(15,75)))!=pfCitadel_cross(p,vec2(15,75),vec2(13,27)))!=pfCitadel_cross(p,vec2(13,27),vec2(16,24)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(13,27), vec2(24,24), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(16,76), vec2(26,75), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(17,24), vec2(19,24), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(12,30),vec2(28,30))!=pfCitadel_cross(p,vec2(28,30),vec2(30,32)))!=pfCitadel_cross(p,vec2(30,32),vec2(30,44)))!=pfCitadel_cross(p,vec2(30,44),vec2(28,46)))!=pfCitadel_cross(p,vec2(28,46),vec2(12,46)))!=pfCitadel_cross(p,vec2(12,46),vec2(10,44)))!=pfCitadel_cross(p,vec2(10,44),vec2(10,32)))!=pfCitadel_cross(p,vec2(10,32),vec2(12,30)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(12,30),vec2(28,30))!=pfCitadel_cross(p,vec2(28,30),vec2(28,32)))!=pfCitadel_cross(p,vec2(28,32),vec2(28,43)))!=pfCitadel_cross(p,vec2(28,43),vec2(12,43)))!=pfCitadel_cross(p,vec2(12,43),vec2(10,32)))!=pfCitadel_cross(p,vec2(10,32),vec2(12,30)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(10,32), vec2(28,30), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(13,44), vec2(29,44), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(13,30), vec2(17,30), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=12.5 && p.x<=27.5 && p.y>=32.5 && p.y<=43.5)) o = pfCitadel_pal[1];
    if((p.x>=13.5 && p.x<=26.5 && p.y>=33.5 && p.y<=34.5)) o = pfCitadel_pal[8];
    if((p.x>=13.5 && p.x<=25.5 && p.y>=34.5 && p.y<=35.5)) o = pfCitadel_pal[9];
    if((p.x>=13.5 && p.x<=26.5 && p.y>=37.5 && p.y<=38.5)) o = pfCitadel_pal[8];
    if((p.x>=13.5 && p.x<=25.5 && p.y>=38.5 && p.y<=39.5)) o = pfCitadel_pal[9];
    if((p.x>=13.5 && p.x<=26.5 && p.y>=41.5 && p.y<=42.5)) o = pfCitadel_pal[8];
    if((p.x>=13.5 && p.x<=25.5 && p.y>=42.5 && p.y<=43.5)) o = pfCitadel_pal[9];
    if((((((((pfCitadel_cross(p,vec2(15,56),vec2(25,56))!=pfCitadel_cross(p,vec2(25,56),vec2(28,59)))!=pfCitadel_cross(p,vec2(28,59),vec2(28,71)))!=pfCitadel_cross(p,vec2(28,71),vec2(25,74)))!=pfCitadel_cross(p,vec2(25,74),vec2(15,74)))!=pfCitadel_cross(p,vec2(15,74),vec2(12,71)))!=pfCitadel_cross(p,vec2(12,71),vec2(12,59)))!=pfCitadel_cross(p,vec2(12,59),vec2(15,56)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(15,56),vec2(25,56))!=pfCitadel_cross(p,vec2(25,56),vec2(26,59)))!=pfCitadel_cross(p,vec2(26,59),vec2(26,71)))!=pfCitadel_cross(p,vec2(26,71),vec2(14,71)))!=pfCitadel_cross(p,vec2(14,71),vec2(12,59)))!=pfCitadel_cross(p,vec2(12,59),vec2(15,56)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(12,59), vec2(25,56), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(15,72), vec2(27,71), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(16,56), vec2(19,56), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=14.5 && p.x<=25.5 && p.y>=58.5 && p.y<=72.5)) o = pfCitadel_pal[1];
    if((p.x>=15.5 && p.x<=24.5 && p.y>=59.5 && p.y<=61.5)) o = pfCitadel_pal[2];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=62.5 && p.y<=69.5)) o = pfCitadel_pal[10];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=62.5 && p.y<=64.5)) o = pfCitadel_pal[11];
    if((p.x>=22.5 && p.x<=23.5 && p.y>=62.5 && p.y<=69.5)) o = pfCitadel_pal[10];
    if((p.x>=22.5 && p.x<=23.5 && p.y>=62.5 && p.y<=64.5)) o = pfCitadel_pal[11];
    if((p.x>=18.5 && p.x<=21.5 && p.y>=70.5 && p.y<=71.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(27,30),vec2(53,30))!=pfCitadel_cross(p,vec2(53,30),vec2(55,33)))!=pfCitadel_cross(p,vec2(55,33),vec2(53,36)))!=pfCitadel_cross(p,vec2(53,36),vec2(27,36)))!=pfCitadel_cross(p,vec2(27,36),vec2(27,30)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(28,30), vec2(52,30), 0.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(27,65),vec2(53,65))!=pfCitadel_cross(p,vec2(53,65),vec2(55,68)))!=pfCitadel_cross(p,vec2(55,68),vec2(53,71)))!=pfCitadel_cross(p,vec2(53,71),vec2(27,71)))!=pfCitadel_cross(p,vec2(27,71),vec2(27,65)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(28,65), vec2(52,65), 0.5)) o = pfCitadel_pal[5];
    if((p.x>=17.5 && p.x<=21.5 && p.y>=19.5 && p.y<=24.5)) o = pfCitadel_pal[3];
    if((p.x>=18.5 && p.x<=20.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(104,24),vec2(112,24))!=pfCitadel_cross(p,vec2(112,24),vec2(115,27)))!=pfCitadel_cross(p,vec2(115,27),vec2(115,75)))!=pfCitadel_cross(p,vec2(115,75),vec2(112,78)))!=pfCitadel_cross(p,vec2(112,78),vec2(104,78)))!=pfCitadel_cross(p,vec2(104,78),vec2(101,75)))!=pfCitadel_cross(p,vec2(101,75),vec2(101,27)))!=pfCitadel_cross(p,vec2(101,27),vec2(104,24)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(104,24),vec2(112,24))!=pfCitadel_cross(p,vec2(112,24),vec2(113,27)))!=pfCitadel_cross(p,vec2(113,27),vec2(113,75)))!=pfCitadel_cross(p,vec2(113,75),vec2(103,75)))!=pfCitadel_cross(p,vec2(103,75),vec2(101,27)))!=pfCitadel_cross(p,vec2(101,27),vec2(104,24)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(101,27), vec2(112,24), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(104,76), vec2(114,75), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(105,24), vec2(107,24), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(101,30),vec2(115,30))!=pfCitadel_cross(p,vec2(115,30),vec2(118,33)))!=pfCitadel_cross(p,vec2(118,33),vec2(118,43)))!=pfCitadel_cross(p,vec2(118,43),vec2(115,46)))!=pfCitadel_cross(p,vec2(115,46),vec2(101,46)))!=pfCitadel_cross(p,vec2(101,46),vec2(98,43)))!=pfCitadel_cross(p,vec2(98,43),vec2(98,33)))!=pfCitadel_cross(p,vec2(98,33),vec2(101,30)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(101,30),vec2(115,30))!=pfCitadel_cross(p,vec2(115,30),vec2(116,33)))!=pfCitadel_cross(p,vec2(116,33),vec2(116,43)))!=pfCitadel_cross(p,vec2(116,43),vec2(100,43)))!=pfCitadel_cross(p,vec2(100,43),vec2(98,33)))!=pfCitadel_cross(p,vec2(98,33),vec2(101,30)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(98,33), vec2(115,30), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(101,44), vec2(117,43), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(102,30), vec2(106,30), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=101.5 && p.x<=113.5 && p.y>=33.5 && p.y<=42.5)) o = pfCitadel_pal[3];
    if((p.x>=103.5 && p.x<=110.5 && p.y>=35.5 && p.y<=36.5)) o = pfCitadel_pal[5];
    if((((((((pfCitadel_cross(p,vec2(103,56),vec2(113,56))!=pfCitadel_cross(p,vec2(113,56),vec2(116,59)))!=pfCitadel_cross(p,vec2(116,59),vec2(116,71)))!=pfCitadel_cross(p,vec2(116,71),vec2(113,74)))!=pfCitadel_cross(p,vec2(113,74),vec2(103,74)))!=pfCitadel_cross(p,vec2(103,74),vec2(100,71)))!=pfCitadel_cross(p,vec2(100,71),vec2(100,59)))!=pfCitadel_cross(p,vec2(100,59),vec2(103,56)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(103,56),vec2(113,56))!=pfCitadel_cross(p,vec2(113,56),vec2(114,59)))!=pfCitadel_cross(p,vec2(114,59),vec2(114,71)))!=pfCitadel_cross(p,vec2(114,71),vec2(102,71)))!=pfCitadel_cross(p,vec2(102,71),vec2(100,59)))!=pfCitadel_cross(p,vec2(100,59),vec2(103,56)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(100,59), vec2(113,56), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(103,72), vec2(115,71), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(104,56), vec2(107,56), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=102.5 && p.x<=113.5 && p.y>=58.5 && p.y<=72.5)) o = pfCitadel_pal[1];
    if((p.x>=103.5 && p.x<=112.5 && p.y>=59.5 && p.y<=61.5)) o = pfCitadel_pal[2];
    if((p.x>=103.5 && p.x<=104.5 && p.y>=62.5 && p.y<=69.5)) o = pfCitadel_pal[10];
    if((p.x>=103.5 && p.x<=104.5 && p.y>=62.5 && p.y<=64.5)) o = pfCitadel_pal[11];
    if((p.x>=110.5 && p.x<=111.5 && p.y>=62.5 && p.y<=69.5)) o = pfCitadel_pal[10];
    if((p.x>=110.5 && p.x<=111.5 && p.y>=62.5 && p.y<=64.5)) o = pfCitadel_pal[11];
    if((p.x>=106.5 && p.x<=109.5 && p.y>=70.5 && p.y<=71.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(80,30),vec2(101,30))!=pfCitadel_cross(p,vec2(101,30),vec2(103,33)))!=pfCitadel_cross(p,vec2(103,33),vec2(101,36)))!=pfCitadel_cross(p,vec2(101,36),vec2(80,36)))!=pfCitadel_cross(p,vec2(80,36),vec2(80,30)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(81,30), vec2(100,30), 0.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(80,65),vec2(101,65))!=pfCitadel_cross(p,vec2(101,65),vec2(103,68)))!=pfCitadel_cross(p,vec2(103,68),vec2(101,71)))!=pfCitadel_cross(p,vec2(101,71),vec2(80,71)))!=pfCitadel_cross(p,vec2(80,71),vec2(80,65)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(81,65), vec2(100,65), 0.5)) o = pfCitadel_pal[5];
    if((p.x>=105.5 && p.x<=109.5 && p.y>=19.5 && p.y<=24.5)) o = pfCitadel_pal[3];
    if((p.x>=106.5 && p.x<=108.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(61,9),vec2(69,9))!=pfCitadel_cross(p,vec2(69,9),vec2(72,12)))!=pfCitadel_cross(p,vec2(72,12),vec2(72,28)))!=pfCitadel_cross(p,vec2(72,28),vec2(69,31)))!=pfCitadel_cross(p,vec2(69,31),vec2(61,31)))!=pfCitadel_cross(p,vec2(61,31),vec2(58,28)))!=pfCitadel_cross(p,vec2(58,28),vec2(58,12)))!=pfCitadel_cross(p,vec2(58,12),vec2(61,9)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(61,9),vec2(69,9))!=pfCitadel_cross(p,vec2(69,9),vec2(70,12)))!=pfCitadel_cross(p,vec2(70,12),vec2(70,28)))!=pfCitadel_cross(p,vec2(70,28),vec2(60,28)))!=pfCitadel_cross(p,vec2(60,28),vec2(58,12)))!=pfCitadel_cross(p,vec2(58,12),vec2(61,9)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(58,12), vec2(69,9), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(61,29), vec2(71,28), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(62,9), vec2(64,9), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(56,17),vec2(75,17))!=pfCitadel_cross(p,vec2(75,17),vec2(77,19)))!=pfCitadel_cross(p,vec2(77,19),vec2(77,23)))!=pfCitadel_cross(p,vec2(77,23),vec2(75,25)))!=pfCitadel_cross(p,vec2(75,25),vec2(56,25)))!=pfCitadel_cross(p,vec2(56,25),vec2(54,23)))!=pfCitadel_cross(p,vec2(54,23),vec2(54,19)))!=pfCitadel_cross(p,vec2(54,19),vec2(56,17)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(56,17),vec2(75,17))!=pfCitadel_cross(p,vec2(75,17),vec2(75,19)))!=pfCitadel_cross(p,vec2(75,19),vec2(75,22)))!=pfCitadel_cross(p,vec2(75,22),vec2(56,22)))!=pfCitadel_cross(p,vec2(56,22),vec2(54,19)))!=pfCitadel_cross(p,vec2(54,19),vec2(56,17)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(54,19), vec2(75,17), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(57,23), vec2(76,23), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(57,17), vec2(61,17), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=57.5 && p.x<=72.5 && p.y>=19.5 && p.y<=21.5)) o = pfCitadel_pal[1];
    if((p.x>=58.5 && p.x<=60.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[10];
    if((p.x>=62.5 && p.x<=64.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[10];
    if((p.x>=66.5 && p.x<=68.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[10];
    if((p.x>=70.5 && p.x<=72.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[10];
    if((p.x>=62.5 && p.x<=64.5 && p.y>=3.5 && p.y<=9.5)) o = pfCitadel_pal[5];
    if((p.x>=63.5 && p.x<=64.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[13];
    if((((((((pfCitadel_cross(p,vec2(74,35),vec2(83,35))!=pfCitadel_cross(p,vec2(83,35),vec2(86,38)))!=pfCitadel_cross(p,vec2(86,38),vec2(86,61)))!=pfCitadel_cross(p,vec2(86,61),vec2(83,64)))!=pfCitadel_cross(p,vec2(83,64),vec2(74,64)))!=pfCitadel_cross(p,vec2(74,64),vec2(71,61)))!=pfCitadel_cross(p,vec2(71,61),vec2(71,38)))!=pfCitadel_cross(p,vec2(71,38),vec2(74,35)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(74,35),vec2(83,35))!=pfCitadel_cross(p,vec2(83,35),vec2(84,38)))!=pfCitadel_cross(p,vec2(84,38),vec2(84,61)))!=pfCitadel_cross(p,vec2(84,61),vec2(73,61)))!=pfCitadel_cross(p,vec2(73,61),vec2(71,38)))!=pfCitadel_cross(p,vec2(71,38),vec2(74,35)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(71,38), vec2(83,35), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(74,62), vec2(85,61), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(75,35), vec2(77,35), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=74.5 && p.x<=80.5 && p.y>=38.5 && p.y<=50.5)) o = pfCitadel_pal[3];
    if((p.x>=74.5 && p.x<=82.5 && p.y>=51.5 && p.y<=59.5)) o = pfCitadel_pal[1];
    if((p.x>=75.5 && p.x<=81.5 && p.y>=52.5 && p.y<=53.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(60,72),vec2(69,72))!=pfCitadel_cross(p,vec2(69,72),vec2(71,74)))!=pfCitadel_cross(p,vec2(71,74),vec2(71,80)))!=pfCitadel_cross(p,vec2(71,80),vec2(69,82)))!=pfCitadel_cross(p,vec2(69,82),vec2(60,82)))!=pfCitadel_cross(p,vec2(60,82),vec2(58,80)))!=pfCitadel_cross(p,vec2(58,80),vec2(58,74)))!=pfCitadel_cross(p,vec2(58,74),vec2(60,72)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(60,72),vec2(69,72))!=pfCitadel_cross(p,vec2(69,72),vec2(69,74)))!=pfCitadel_cross(p,vec2(69,74),vec2(69,79)))!=pfCitadel_cross(p,vec2(69,79),vec2(60,79)))!=pfCitadel_cross(p,vec2(60,79),vec2(58,74)))!=pfCitadel_cross(p,vec2(58,74),vec2(60,72)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(58,74), vec2(69,72), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(61,80), vec2(70,80), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(61,72), vec2(63,72), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=60.5 && p.x<=68.5 && p.y>=77.5 && p.y<=80.5)) o = pfCitadel_pal[1];
    if((p.x>=61.5 && p.x<=66.5 && p.y>=78.5 && p.y<=79.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(33,27),vec2(41,27))!=pfCitadel_cross(p,vec2(41,27),vec2(44,30)))!=pfCitadel_cross(p,vec2(44,30),vec2(44,37)))!=pfCitadel_cross(p,vec2(44,37),vec2(41,40)))!=pfCitadel_cross(p,vec2(41,40),vec2(33,40)))!=pfCitadel_cross(p,vec2(33,40),vec2(30,37)))!=pfCitadel_cross(p,vec2(30,37),vec2(30,30)))!=pfCitadel_cross(p,vec2(30,30),vec2(33,27)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(33,27),vec2(41,27))!=pfCitadel_cross(p,vec2(41,27),vec2(42,30)))!=pfCitadel_cross(p,vec2(42,30),vec2(42,37)))!=pfCitadel_cross(p,vec2(42,37),vec2(32,37)))!=pfCitadel_cross(p,vec2(32,37),vec2(30,30)))!=pfCitadel_cross(p,vec2(30,30),vec2(33,27)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(30,30), vec2(41,27), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(33,38), vec2(43,37), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(34,27), vec2(36,27), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(35,22),vec2(39,22))!=pfCitadel_cross(p,vec2(39,22),vec2(41,24)))!=pfCitadel_cross(p,vec2(41,24),vec2(41,29)))!=pfCitadel_cross(p,vec2(41,29),vec2(39,31)))!=pfCitadel_cross(p,vec2(39,31),vec2(35,31)))!=pfCitadel_cross(p,vec2(35,31),vec2(33,29)))!=pfCitadel_cross(p,vec2(33,29),vec2(33,24)))!=pfCitadel_cross(p,vec2(33,24),vec2(35,22)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(35,22),vec2(39,22))!=pfCitadel_cross(p,vec2(39,22),vec2(39,24)))!=pfCitadel_cross(p,vec2(39,24),vec2(39,28)))!=pfCitadel_cross(p,vec2(39,28),vec2(35,28)))!=pfCitadel_cross(p,vec2(35,28),vec2(33,24)))!=pfCitadel_cross(p,vec2(33,24),vec2(35,22)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(33,24), vec2(39,22), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(36,29), vec2(40,29), 0.5)) o = pfCitadel_pal[1];
    if((p.x>=35.5 && p.x<=37.5 && p.y>=19.5 && p.y<=25.5)) o = pfCitadel_pal[5];
    if((p.x>=32.5 && p.x<=40.5 && p.y>=32.5 && p.y<=35.5)) o = pfCitadel_pal[1];
    if((p.x>=33.5 && p.x<=38.5 && p.y>=32.5 && p.y<=33.5)) o = pfCitadel_pal[10];
    if((((((((pfCitadel_cross(p,vec2(87,27),vec2(95,27))!=pfCitadel_cross(p,vec2(95,27),vec2(98,30)))!=pfCitadel_cross(p,vec2(98,30),vec2(98,37)))!=pfCitadel_cross(p,vec2(98,37),vec2(95,40)))!=pfCitadel_cross(p,vec2(95,40),vec2(87,40)))!=pfCitadel_cross(p,vec2(87,40),vec2(84,37)))!=pfCitadel_cross(p,vec2(84,37),vec2(84,30)))!=pfCitadel_cross(p,vec2(84,30),vec2(87,27)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(87,27),vec2(95,27))!=pfCitadel_cross(p,vec2(95,27),vec2(96,30)))!=pfCitadel_cross(p,vec2(96,30),vec2(96,37)))!=pfCitadel_cross(p,vec2(96,37),vec2(86,37)))!=pfCitadel_cross(p,vec2(86,37),vec2(84,30)))!=pfCitadel_cross(p,vec2(84,30),vec2(87,27)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(84,30), vec2(95,27), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(87,38), vec2(97,37), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(88,27), vec2(90,27), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(89,22),vec2(93,22))!=pfCitadel_cross(p,vec2(93,22),vec2(95,24)))!=pfCitadel_cross(p,vec2(95,24),vec2(95,29)))!=pfCitadel_cross(p,vec2(95,29),vec2(93,31)))!=pfCitadel_cross(p,vec2(93,31),vec2(89,31)))!=pfCitadel_cross(p,vec2(89,31),vec2(87,29)))!=pfCitadel_cross(p,vec2(87,29),vec2(87,24)))!=pfCitadel_cross(p,vec2(87,24),vec2(89,22)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(89,22),vec2(93,22))!=pfCitadel_cross(p,vec2(93,22),vec2(93,24)))!=pfCitadel_cross(p,vec2(93,24),vec2(93,28)))!=pfCitadel_cross(p,vec2(93,28),vec2(89,28)))!=pfCitadel_cross(p,vec2(89,28),vec2(87,24)))!=pfCitadel_cross(p,vec2(87,24),vec2(89,22)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(87,24), vec2(93,22), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(90,29), vec2(94,29), 0.5)) o = pfCitadel_pal[1];
    if((p.x>=89.5 && p.x<=91.5 && p.y>=19.5 && p.y<=25.5)) o = pfCitadel_pal[5];
    if((p.x>=86.5 && p.x<=94.5 && p.y>=32.5 && p.y<=35.5)) o = pfCitadel_pal[1];
    if((p.x>=87.5 && p.x<=92.5 && p.y>=32.5 && p.y<=33.5)) o = pfCitadel_pal[10];
    if((((((((pfCitadel_cross(p,vec2(55,77),vec2(73,77))!=pfCitadel_cross(p,vec2(73,77),vec2(76,80)))!=pfCitadel_cross(p,vec2(76,80),vec2(76,83)))!=pfCitadel_cross(p,vec2(76,83),vec2(73,86)))!=pfCitadel_cross(p,vec2(73,86),vec2(55,86)))!=pfCitadel_cross(p,vec2(55,86),vec2(52,83)))!=pfCitadel_cross(p,vec2(52,83),vec2(52,80)))!=pfCitadel_cross(p,vec2(52,80),vec2(55,77)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(55,77),vec2(73,77))!=pfCitadel_cross(p,vec2(73,77),vec2(74,80)))!=pfCitadel_cross(p,vec2(74,80),vec2(74,83)))!=pfCitadel_cross(p,vec2(74,83),vec2(54,83)))!=pfCitadel_cross(p,vec2(54,83),vec2(52,80)))!=pfCitadel_cross(p,vec2(52,80),vec2(55,77)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(52,80), vec2(73,77), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(55,84), vec2(75,83), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(56,77), vec2(61,77), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=57.5 && p.x<=69.5 && p.y>=79.5 && p.y<=82.5)) o = pfCitadel_pal[1];
    if((p.x>=67.5 && p.x<=70.5 && p.y>=64.5 && p.y<=68.5)) o = pfCitadel_pal[2];
    if((p.x>=67.5 && p.x<=70.5 && p.y>=64.5 && p.y<=65.5)) o = pfCitadel_pal[5];
    if((p.x>=72.5 && p.x<=75.5 && p.y>=44.5 && p.y<=48.5)) o = pfCitadel_pal[2];
    if((p.x>=72.5 && p.x<=75.5 && p.y>=44.5 && p.y<=45.5)) o = pfCitadel_pal[5];
    return o;
}
void mainImage(out vec4 fragColor, in vec2 fragCoord){
    float pp=2.0;
    vec2 origin=vec2(iResolution.x*0.5-128.0*pp, iResolution.y*0.5-96.0*pp);
    vec2 sp=floor((fragCoord-origin)/pp)+0.5;
    if(iTime>1e9) sp=vec2(-999.0);
    vec3 c=pfCitadel(sp, vec2(1.0,1.0));
    float a=clamp(max(max(c.r,c.g),c.b)*255.0,0.0,1.0);
    fragColor=vec4(mix(vec3(8.0,10.0,16.0)/255.0,c,a),1.0);
}
