// Generated by pixel_foundry_proc/emit.py - rules, not pixels.
// sp: source pixels on the 128x96 design grid (origin top-left). light: unit vector.
const vec3 pfCitadel_pal[14] = vec3[14](
    vec3(0,0,0)/255.0,
    vec3(13,17,26)/255.0,
    vec3(23,29,40)/255.0,
    vec3(35,44,56)/255.0,
    vec3(49,61,72)/255.0,
    vec3(69,80,87)/255.0,
    vec3(99,108,109)/255.0,
    vec3(143,153,148)/255.0,
    vec3(33,38,55)/255.0,
    vec3(52,56,74)/255.0,
    vec3(112,101,72)/255.0,
    vec3(177,157,105)/255.0,
    vec3(45,76,80)/255.0,
    vec3(103,151,143)/255.0);
bool pfCitadel_cross(vec2 p, vec2 a, vec2 b) {
    return ((a.y > p.y) != (b.y > p.y)) &&
           (p.x < (b.x - a.x) * (p.y - a.y) / (b.y - a.y == 0.0 ? 1e-6 : (b.y - a.y)) + a.x);
}

bool pfCitadel_seg(vec2 p, vec2 a, vec2 b, float w) {
    vec2 pa = p - a, ba = b - a;
    float h = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-6), 0.0, 1.0);
    return length(pa - ba * h) <= w;
}

bool pfCitadel_oct(vec2 p, vec2 c, vec2 h, float bevel) {
    vec2 q = abs(p - c) - (h - bevel);
    return (length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0)) - bevel <= 0.0;
}
vec3 pfCitadel(vec2 sp, vec2 light) {
    vec3 o = vec3(0.0);
    vec2 p = sp;
    float lit = clamp(0.5 + 0.5 * dot(normalize(light + vec2(1e-4, 1e-4)), vec2(0.7071, 0.7071)), 0.0, 1.0);
    if((p.x>=3.5 && p.x<=28.5 && p.y>=11.5 && p.y<=14.5)) o = pfCitadel_pal[2];
    if((p.x>=3.5 && p.x<=28.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[5];
    if(pfCitadel_seg(p, vec2(6,12), vec2(8,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(8,12), vec2(8,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(10,12), vec2(12,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(12,12), vec2(12,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,12), vec2(16,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(16,12), vec2(16,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(18,12), vec2(20,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(20,12), vec2(20,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(22,12), vec2(24,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(24,12), vec2(24,14), 0.5)) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(26,12), vec2(28,14), 0.5)) o = pfCitadel_pal[4];
    if((((((((pfCitadel_cross(p,vec2(12,8),vec2(18,8))!=pfCitadel_cross(p,vec2(18,8),vec2(18,8)))!=pfCitadel_cross(p,vec2(18,8),vec2(18,18)))!=pfCitadel_cross(p,vec2(18,18),vec2(18,20)))!=pfCitadel_cross(p,vec2(18,20),vec2(12,20)))!=pfCitadel_cross(p,vec2(12,20),vec2(12,18)))!=pfCitadel_cross(p,vec2(12,18),vec2(12,8)))!=pfCitadel_cross(p,vec2(12,8),vec2(12,8)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(12,8),vec2(18,8))!=pfCitadel_cross(p,vec2(18,8),vec2(18,8)))!=pfCitadel_cross(p,vec2(18,8),vec2(18,18)))!=pfCitadel_cross(p,vec2(18,18),vec2(12,18)))!=pfCitadel_cross(p,vec2(12,18),vec2(12,8)))!=pfCitadel_cross(p,vec2(12,8),vec2(12,8)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(12,8), vec2(18,8), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(12,18), vec2(18,18), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(14,8), vec2(14,8), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(12,10),vec2(12,10))!=pfCitadel_cross(p,vec2(12,10),vec2(14,10)))!=pfCitadel_cross(p,vec2(14,10),vec2(14,16)))!=pfCitadel_cross(p,vec2(14,16),vec2(12,16)))!=pfCitadel_cross(p,vec2(12,16),vec2(12,16)))!=pfCitadel_cross(p,vec2(12,16),vec2(10,16)))!=pfCitadel_cross(p,vec2(10,16),vec2(10,10)))!=pfCitadel_cross(p,vec2(10,10),vec2(12,10)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(12,10),vec2(12,10))!=pfCitadel_cross(p,vec2(12,10),vec2(12,10)))!=pfCitadel_cross(p,vec2(12,10),vec2(12,16)))!=pfCitadel_cross(p,vec2(12,16),vec2(12,16)))!=pfCitadel_cross(p,vec2(12,16),vec2(10,10)))!=pfCitadel_cross(p,vec2(10,10),vec2(12,10)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(10,10), vec2(12,10), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(12,16), vec2(14,16), 0.5)) o = pfCitadel_pal[1];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=9.5 && p.y<=16.5)) o = pfCitadel_pal[1];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=9.5 && p.y<=10.5)) o = pfCitadel_pal[8];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=9.5 && p.y<=10.5)) o = pfCitadel_pal[9];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[8];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[9];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[8];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[9];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=13.5 && p.y<=14.5)) o = pfCitadel_pal[8];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=13.5 && p.y<=14.5)) o = pfCitadel_pal[9];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=13.5 && p.y<=14.5)) o = pfCitadel_pal[8];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=13.5 && p.y<=14.5)) o = pfCitadel_pal[9];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[8];
    if((p.x>=11.5 && p.x<=12.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[9];
    if((p.x>=13.5 && p.x<=16.5 && p.y>=7.5 && p.y<=18.5)) o = pfCitadel_pal[2];
    if((((((((pfCitadel_cross(p,vec2(14,8),vec2(16,8))!=pfCitadel_cross(p,vec2(16,8),vec2(16,10)))!=pfCitadel_cross(p,vec2(16,10),vec2(16,10)))!=pfCitadel_cross(p,vec2(16,10),vec2(16,12)))!=pfCitadel_cross(p,vec2(16,12),vec2(14,12)))!=pfCitadel_cross(p,vec2(14,12),vec2(14,10)))!=pfCitadel_cross(p,vec2(14,10),vec2(14,10)))!=pfCitadel_cross(p,vec2(14,10),vec2(14,8)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(14,8),vec2(16,8))!=pfCitadel_cross(p,vec2(16,8),vec2(16,10)))!=pfCitadel_cross(p,vec2(16,10),vec2(16,10)))!=pfCitadel_cross(p,vec2(16,10),vec2(16,10)))!=pfCitadel_cross(p,vec2(16,10),vec2(14,10)))!=pfCitadel_cross(p,vec2(14,10),vec2(14,8)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,10), vec2(16,8), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(16,10), vec2(16,10), 0.5)) o = pfCitadel_pal[1];
    if((((((((pfCitadel_cross(p,vec2(14,12),vec2(16,12))!=pfCitadel_cross(p,vec2(16,12),vec2(16,12)))!=pfCitadel_cross(p,vec2(16,12),vec2(16,14)))!=pfCitadel_cross(p,vec2(16,14),vec2(16,14)))!=pfCitadel_cross(p,vec2(16,14),vec2(14,14)))!=pfCitadel_cross(p,vec2(14,14),vec2(14,14)))!=pfCitadel_cross(p,vec2(14,14),vec2(14,12)))!=pfCitadel_cross(p,vec2(14,12),vec2(14,12)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(14,12),vec2(16,12))!=pfCitadel_cross(p,vec2(16,12),vec2(16,12)))!=pfCitadel_cross(p,vec2(16,12),vec2(16,14)))!=pfCitadel_cross(p,vec2(16,14),vec2(16,14)))!=pfCitadel_cross(p,vec2(16,14),vec2(14,12)))!=pfCitadel_cross(p,vec2(14,12),vec2(14,12)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,12), vec2(16,12), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(16,14), vec2(16,14), 0.5)) o = pfCitadel_pal[1];
    if((((((((pfCitadel_cross(p,vec2(14,16),vec2(16,16))!=pfCitadel_cross(p,vec2(16,16),vec2(16,16)))!=pfCitadel_cross(p,vec2(16,16),vec2(16,16)))!=pfCitadel_cross(p,vec2(16,16),vec2(16,16)))!=pfCitadel_cross(p,vec2(16,16),vec2(14,16)))!=pfCitadel_cross(p,vec2(14,16),vec2(14,16)))!=pfCitadel_cross(p,vec2(14,16),vec2(14,16)))!=pfCitadel_cross(p,vec2(14,16),vec2(14,16)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(14,16),vec2(16,16))!=pfCitadel_cross(p,vec2(16,16),vec2(16,16)))!=pfCitadel_cross(p,vec2(16,16),vec2(16,16)))!=pfCitadel_cross(p,vec2(16,16),vec2(16,16)))!=pfCitadel_cross(p,vec2(16,16),vec2(14,16)))!=pfCitadel_cross(p,vec2(14,16),vec2(14,16)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,16), vec2(16,16), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(16,16), vec2(16,16), 0.5)) o = pfCitadel_pal[1];
    if((((((((pfCitadel_cross(p,vec2(4,6),vec2(6,6))!=pfCitadel_cross(p,vec2(6,6),vec2(6,6)))!=pfCitadel_cross(p,vec2(6,6),vec2(6,18)))!=pfCitadel_cross(p,vec2(6,18),vec2(6,20)))!=pfCitadel_cross(p,vec2(6,20),vec2(4,20)))!=pfCitadel_cross(p,vec2(4,20),vec2(4,18)))!=pfCitadel_cross(p,vec2(4,18),vec2(4,6)))!=pfCitadel_cross(p,vec2(4,6),vec2(4,6)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(4,6),vec2(6,6))!=pfCitadel_cross(p,vec2(6,6),vec2(6,6)))!=pfCitadel_cross(p,vec2(6,6),vec2(6,18)))!=pfCitadel_cross(p,vec2(6,18),vec2(4,18)))!=pfCitadel_cross(p,vec2(4,18),vec2(4,6)))!=pfCitadel_cross(p,vec2(4,6),vec2(4,6)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(4,6), vec2(6,6), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(4,20), vec2(6,18), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(4,6), vec2(4,6), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(4,8),vec2(8,8))!=pfCitadel_cross(p,vec2(8,8),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,12)))!=pfCitadel_cross(p,vec2(8,12),vec2(8,12)))!=pfCitadel_cross(p,vec2(8,12),vec2(4,12)))!=pfCitadel_cross(p,vec2(4,12),vec2(2,12)))!=pfCitadel_cross(p,vec2(2,12),vec2(2,8)))!=pfCitadel_cross(p,vec2(2,8),vec2(4,8)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(4,8),vec2(8,8))!=pfCitadel_cross(p,vec2(8,8),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,10)))!=pfCitadel_cross(p,vec2(8,10),vec2(4,10)))!=pfCitadel_cross(p,vec2(4,10),vec2(2,8)))!=pfCitadel_cross(p,vec2(2,8),vec2(4,8)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(2,8), vec2(8,8), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(4,12), vec2(8,12), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(4,8), vec2(4,8), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=7.5 && p.y<=10.5)) o = pfCitadel_pal[1];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[8];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[9];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=9.5 && p.y<=10.5)) o = pfCitadel_pal[8];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=9.5 && p.y<=10.5)) o = pfCitadel_pal[9];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=9.5 && p.y<=10.5)) o = pfCitadel_pal[8];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=9.5 && p.y<=10.5)) o = pfCitadel_pal[9];
    if((((((((pfCitadel_cross(p,vec2(4,14),vec2(6,14))!=pfCitadel_cross(p,vec2(6,14),vec2(8,14)))!=pfCitadel_cross(p,vec2(8,14),vec2(8,18)))!=pfCitadel_cross(p,vec2(8,18),vec2(6,18)))!=pfCitadel_cross(p,vec2(6,18),vec2(4,18)))!=pfCitadel_cross(p,vec2(4,18),vec2(4,18)))!=pfCitadel_cross(p,vec2(4,18),vec2(4,14)))!=pfCitadel_cross(p,vec2(4,14),vec2(4,14)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(4,14),vec2(6,14))!=pfCitadel_cross(p,vec2(6,14),vec2(6,14)))!=pfCitadel_cross(p,vec2(6,14),vec2(6,18)))!=pfCitadel_cross(p,vec2(6,18),vec2(4,18)))!=pfCitadel_cross(p,vec2(4,18),vec2(4,14)))!=pfCitadel_cross(p,vec2(4,14),vec2(4,14)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(4,14), vec2(6,14), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(4,18), vec2(6,18), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(4,14), vec2(4,14), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=13.5 && p.y<=18.5)) o = pfCitadel_pal[1];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[2];
    if((p.x>=3.5 && p.x<=4.5 && p.y>=15.5 && p.y<=18.5)) o = pfCitadel_pal[10];
    if((p.x>=3.5 && p.x<=4.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[11];
    if((p.x>=5.5 && p.x<=6.5 && p.y>=15.5 && p.y<=18.5)) o = pfCitadel_pal[10];
    if((p.x>=5.5 && p.x<=6.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[11];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=17.5 && p.y<=18.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(6,8),vec2(14,8))!=pfCitadel_cross(p,vec2(14,8),vec2(14,8)))!=pfCitadel_cross(p,vec2(14,8),vec2(14,8)))!=pfCitadel_cross(p,vec2(14,8),vec2(6,8)))!=pfCitadel_cross(p,vec2(6,8),vec2(6,8)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(8,8), vec2(12,8), 0.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(6,16),vec2(14,16))!=pfCitadel_cross(p,vec2(14,16),vec2(14,16)))!=pfCitadel_cross(p,vec2(14,16),vec2(14,18)))!=pfCitadel_cross(p,vec2(14,18),vec2(6,18)))!=pfCitadel_cross(p,vec2(6,18),vec2(6,16)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(8,16), vec2(12,16), 0.5)) o = pfCitadel_pal[5];
    if((p.x>=3.5 && p.x<=6.5 && p.y>=3.5 && p.y<=6.5)) o = pfCitadel_pal[3];
    if((p.x>=3.5 && p.x<=4.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(26,6),vec2(28,6))!=pfCitadel_cross(p,vec2(28,6),vec2(28,6)))!=pfCitadel_cross(p,vec2(28,6),vec2(28,18)))!=pfCitadel_cross(p,vec2(28,18),vec2(28,20)))!=pfCitadel_cross(p,vec2(28,20),vec2(26,20)))!=pfCitadel_cross(p,vec2(26,20),vec2(26,18)))!=pfCitadel_cross(p,vec2(26,18),vec2(26,6)))!=pfCitadel_cross(p,vec2(26,6),vec2(26,6)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(26,6),vec2(28,6))!=pfCitadel_cross(p,vec2(28,6),vec2(28,6)))!=pfCitadel_cross(p,vec2(28,6),vec2(28,18)))!=pfCitadel_cross(p,vec2(28,18),vec2(26,18)))!=pfCitadel_cross(p,vec2(26,18),vec2(26,6)))!=pfCitadel_cross(p,vec2(26,6),vec2(26,6)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(26,6), vec2(28,6), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(26,20), vec2(28,18), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(26,6), vec2(26,6), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(26,8),vec2(28,8))!=pfCitadel_cross(p,vec2(28,8),vec2(30,8)))!=pfCitadel_cross(p,vec2(30,8),vec2(30,10)))!=pfCitadel_cross(p,vec2(30,10),vec2(28,12)))!=pfCitadel_cross(p,vec2(28,12),vec2(26,12)))!=pfCitadel_cross(p,vec2(26,12),vec2(24,10)))!=pfCitadel_cross(p,vec2(24,10),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(26,8)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(26,8),vec2(28,8))!=pfCitadel_cross(p,vec2(28,8),vec2(28,8)))!=pfCitadel_cross(p,vec2(28,8),vec2(28,10)))!=pfCitadel_cross(p,vec2(28,10),vec2(24,10)))!=pfCitadel_cross(p,vec2(24,10),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(26,8)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(24,8), vec2(28,8), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(26,12), vec2(30,10), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(26,8), vec2(26,8), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=7.5 && p.y<=10.5)) o = pfCitadel_pal[3];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[5];
    if((((((((pfCitadel_cross(p,vec2(26,14),vec2(28,14))!=pfCitadel_cross(p,vec2(28,14),vec2(28,14)))!=pfCitadel_cross(p,vec2(28,14),vec2(28,18)))!=pfCitadel_cross(p,vec2(28,18),vec2(28,18)))!=pfCitadel_cross(p,vec2(28,18),vec2(26,18)))!=pfCitadel_cross(p,vec2(26,18),vec2(24,18)))!=pfCitadel_cross(p,vec2(24,18),vec2(24,14)))!=pfCitadel_cross(p,vec2(24,14),vec2(26,14)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(26,14),vec2(28,14))!=pfCitadel_cross(p,vec2(28,14),vec2(28,14)))!=pfCitadel_cross(p,vec2(28,14),vec2(28,18)))!=pfCitadel_cross(p,vec2(28,18),vec2(26,18)))!=pfCitadel_cross(p,vec2(26,18),vec2(24,14)))!=pfCitadel_cross(p,vec2(24,14),vec2(26,14)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(24,14), vec2(28,14), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(26,18), vec2(28,18), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(26,14), vec2(26,14), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=13.5 && p.y<=18.5)) o = pfCitadel_pal[1];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[2];
    if((p.x>=25.5 && p.x<=26.5 && p.y>=15.5 && p.y<=18.5)) o = pfCitadel_pal[10];
    if((p.x>=25.5 && p.x<=26.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[11];
    if((p.x>=27.5 && p.x<=28.5 && p.y>=15.5 && p.y<=18.5)) o = pfCitadel_pal[10];
    if((p.x>=27.5 && p.x<=28.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[11];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=17.5 && p.y<=18.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(20,8),vec2(26,8))!=pfCitadel_cross(p,vec2(26,8),vec2(26,8)))!=pfCitadel_cross(p,vec2(26,8),vec2(26,8)))!=pfCitadel_cross(p,vec2(26,8),vec2(20,8)))!=pfCitadel_cross(p,vec2(20,8),vec2(20,8)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(20,8), vec2(24,8), 0.5)) o = pfCitadel_pal[5];
    if(((((pfCitadel_cross(p,vec2(20,16),vec2(26,16))!=pfCitadel_cross(p,vec2(26,16),vec2(26,16)))!=pfCitadel_cross(p,vec2(26,16),vec2(26,18)))!=pfCitadel_cross(p,vec2(26,18),vec2(20,18)))!=pfCitadel_cross(p,vec2(20,18),vec2(20,16)))) o = pfCitadel_pal[3];
    if(pfCitadel_seg(p, vec2(20,16), vec2(24,16), 0.5)) o = pfCitadel_pal[5];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=3.5 && p.y<=6.5)) o = pfCitadel_pal[3];
    if((p.x>=25.5 && p.x<=28.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(16,2),vec2(18,2))!=pfCitadel_cross(p,vec2(18,2),vec2(18,4)))!=pfCitadel_cross(p,vec2(18,4),vec2(18,8)))!=pfCitadel_cross(p,vec2(18,8),vec2(18,8)))!=pfCitadel_cross(p,vec2(18,8),vec2(16,8)))!=pfCitadel_cross(p,vec2(16,8),vec2(14,8)))!=pfCitadel_cross(p,vec2(14,8),vec2(14,4)))!=pfCitadel_cross(p,vec2(14,4),vec2(16,2)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(16,2),vec2(18,2))!=pfCitadel_cross(p,vec2(18,2),vec2(18,4)))!=pfCitadel_cross(p,vec2(18,4),vec2(18,8)))!=pfCitadel_cross(p,vec2(18,8),vec2(16,8)))!=pfCitadel_cross(p,vec2(16,8),vec2(14,4)))!=pfCitadel_cross(p,vec2(14,4),vec2(16,2)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,4), vec2(18,2), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(16,8), vec2(18,8), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(16,2), vec2(16,2), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(14,4),vec2(18,4))!=pfCitadel_cross(p,vec2(18,4),vec2(20,4)))!=pfCitadel_cross(p,vec2(20,4),vec2(20,6)))!=pfCitadel_cross(p,vec2(20,6),vec2(18,6)))!=pfCitadel_cross(p,vec2(18,6),vec2(14,6)))!=pfCitadel_cross(p,vec2(14,6),vec2(14,6)))!=pfCitadel_cross(p,vec2(14,6),vec2(14,4)))!=pfCitadel_cross(p,vec2(14,4),vec2(14,4)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(14,4),vec2(18,4))!=pfCitadel_cross(p,vec2(18,4),vec2(18,4)))!=pfCitadel_cross(p,vec2(18,4),vec2(18,6)))!=pfCitadel_cross(p,vec2(18,6),vec2(14,6)))!=pfCitadel_cross(p,vec2(14,6),vec2(14,4)))!=pfCitadel_cross(p,vec2(14,4),vec2(14,4)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,4), vec2(18,4), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(14,6), vec2(20,6), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(14,4), vec2(16,4), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=13.5 && p.x<=18.5 && p.y>=3.5 && p.y<=6.5)) o = pfCitadel_pal[1];
    if((p.x>=13.5 && p.x<=16.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[10];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[10];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[10];
    if((p.x>=17.5 && p.x<=18.5 && p.y>=3.5 && p.y<=4.5)) o = pfCitadel_pal[10];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=-0.5 && p.y<=2.5)) o = pfCitadel_pal[5];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=-0.5 && p.y<=0.5)) o = pfCitadel_pal[13];
    if((((((((pfCitadel_cross(p,vec2(18,8),vec2(20,8))!=pfCitadel_cross(p,vec2(20,8),vec2(22,10)))!=pfCitadel_cross(p,vec2(22,10),vec2(22,16)))!=pfCitadel_cross(p,vec2(22,16),vec2(20,16)))!=pfCitadel_cross(p,vec2(20,16),vec2(18,16)))!=pfCitadel_cross(p,vec2(18,16),vec2(18,16)))!=pfCitadel_cross(p,vec2(18,16),vec2(18,10)))!=pfCitadel_cross(p,vec2(18,10),vec2(18,8)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(18,8),vec2(20,8))!=pfCitadel_cross(p,vec2(20,8),vec2(20,10)))!=pfCitadel_cross(p,vec2(20,10),vec2(20,16)))!=pfCitadel_cross(p,vec2(20,16),vec2(18,16)))!=pfCitadel_cross(p,vec2(18,16),vec2(18,10)))!=pfCitadel_cross(p,vec2(18,10),vec2(18,8)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(18,10), vec2(20,8), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(18,16), vec2(22,16), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(18,8), vec2(20,8), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=17.5 && p.x<=20.5 && p.y>=9.5 && p.y<=12.5)) o = pfCitadel_pal[3];
    if((p.x>=17.5 && p.x<=20.5 && p.y>=11.5 && p.y<=14.5)) o = pfCitadel_pal[1];
    if((p.x>=19.5 && p.x<=20.5 && p.y>=13.5 && p.y<=14.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(16,18),vec2(18,18))!=pfCitadel_cross(p,vec2(18,18),vec2(18,18)))!=pfCitadel_cross(p,vec2(18,18),vec2(18,20)))!=pfCitadel_cross(p,vec2(18,20),vec2(18,20)))!=pfCitadel_cross(p,vec2(18,20),vec2(16,20)))!=pfCitadel_cross(p,vec2(16,20),vec2(14,20)))!=pfCitadel_cross(p,vec2(14,20),vec2(14,18)))!=pfCitadel_cross(p,vec2(14,18),vec2(16,18)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(16,18),vec2(18,18))!=pfCitadel_cross(p,vec2(18,18),vec2(18,18)))!=pfCitadel_cross(p,vec2(18,18),vec2(18,20)))!=pfCitadel_cross(p,vec2(18,20),vec2(16,20)))!=pfCitadel_cross(p,vec2(16,20),vec2(14,18)))!=pfCitadel_cross(p,vec2(14,18),vec2(16,18)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(14,18), vec2(18,18), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(16,20), vec2(18,20), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(16,18), vec2(16,18), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[1];
    if((p.x>=15.5 && p.x<=16.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[12];
    if((((((((pfCitadel_cross(p,vec2(8,6),vec2(10,6))!=pfCitadel_cross(p,vec2(10,6),vec2(12,8)))!=pfCitadel_cross(p,vec2(12,8),vec2(12,10)))!=pfCitadel_cross(p,vec2(12,10),vec2(10,10)))!=pfCitadel_cross(p,vec2(10,10),vec2(8,10)))!=pfCitadel_cross(p,vec2(8,10),vec2(8,10)))!=pfCitadel_cross(p,vec2(8,10),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,6)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(8,6),vec2(10,6))!=pfCitadel_cross(p,vec2(10,6),vec2(10,8)))!=pfCitadel_cross(p,vec2(10,8),vec2(10,10)))!=pfCitadel_cross(p,vec2(10,10),vec2(8,10)))!=pfCitadel_cross(p,vec2(8,10),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,6)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(8,8), vec2(10,6), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(8,10), vec2(10,10), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(8,6), vec2(8,6), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(8,6),vec2(10,6))!=pfCitadel_cross(p,vec2(10,6),vec2(10,6)))!=pfCitadel_cross(p,vec2(10,6),vec2(10,8)))!=pfCitadel_cross(p,vec2(10,8),vec2(10,8)))!=pfCitadel_cross(p,vec2(10,8),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,6)))!=pfCitadel_cross(p,vec2(8,6),vec2(8,6)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(8,6),vec2(10,6))!=pfCitadel_cross(p,vec2(10,6),vec2(10,6)))!=pfCitadel_cross(p,vec2(10,6),vec2(10,8)))!=pfCitadel_cross(p,vec2(10,8),vec2(8,8)))!=pfCitadel_cross(p,vec2(8,8),vec2(8,6)))!=pfCitadel_cross(p,vec2(8,6),vec2(8,6)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(8,6), vec2(10,6), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(8,8), vec2(10,8), 0.5)) o = pfCitadel_pal[1];
    if((p.x>=7.5 && p.x<=10.5 && p.y>=3.5 && p.y<=6.5)) o = pfCitadel_pal[5];
    if((p.x>=7.5 && p.x<=10.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[1];
    if((p.x>=7.5 && p.x<=10.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[10];
    if((((((((pfCitadel_cross(p,vec2(22,6),vec2(24,6))!=pfCitadel_cross(p,vec2(24,6),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(24,10)))!=pfCitadel_cross(p,vec2(24,10),vec2(24,10)))!=pfCitadel_cross(p,vec2(24,10),vec2(22,10)))!=pfCitadel_cross(p,vec2(22,10),vec2(20,10)))!=pfCitadel_cross(p,vec2(20,10),vec2(20,8)))!=pfCitadel_cross(p,vec2(20,8),vec2(22,6)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(22,6),vec2(24,6))!=pfCitadel_cross(p,vec2(24,6),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(24,10)))!=pfCitadel_cross(p,vec2(24,10),vec2(22,10)))!=pfCitadel_cross(p,vec2(22,10),vec2(20,8)))!=pfCitadel_cross(p,vec2(20,8),vec2(22,6)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(20,8), vec2(24,6), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(22,10), vec2(24,10), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(22,6), vec2(22,6), 0.5)) o = pfCitadel_pal[7];
    if((((((((pfCitadel_cross(p,vec2(22,6),vec2(24,6))!=pfCitadel_cross(p,vec2(24,6),vec2(24,6)))!=pfCitadel_cross(p,vec2(24,6),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(22,8)))!=pfCitadel_cross(p,vec2(22,8),vec2(22,8)))!=pfCitadel_cross(p,vec2(22,8),vec2(22,6)))!=pfCitadel_cross(p,vec2(22,6),vec2(22,6)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(22,6),vec2(24,6))!=pfCitadel_cross(p,vec2(24,6),vec2(24,6)))!=pfCitadel_cross(p,vec2(24,6),vec2(24,8)))!=pfCitadel_cross(p,vec2(24,8),vec2(22,8)))!=pfCitadel_cross(p,vec2(22,8),vec2(22,6)))!=pfCitadel_cross(p,vec2(22,6),vec2(22,6)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(22,6), vec2(24,6), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(22,8), vec2(24,8), 0.5)) o = pfCitadel_pal[1];
    if((p.x>=21.5 && p.x<=22.5 && p.y>=3.5 && p.y<=6.5)) o = pfCitadel_pal[5];
    if((p.x>=21.5 && p.x<=24.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[1];
    if((p.x>=21.5 && p.x<=24.5 && p.y>=7.5 && p.y<=8.5)) o = pfCitadel_pal[10];
    if((((((((pfCitadel_cross(p,vec2(14,20),vec2(18,20))!=pfCitadel_cross(p,vec2(18,20),vec2(20,20)))!=pfCitadel_cross(p,vec2(20,20),vec2(20,20)))!=pfCitadel_cross(p,vec2(20,20),vec2(18,22)))!=pfCitadel_cross(p,vec2(18,22),vec2(14,22)))!=pfCitadel_cross(p,vec2(14,22),vec2(12,20)))!=pfCitadel_cross(p,vec2(12,20),vec2(12,20)))!=pfCitadel_cross(p,vec2(12,20),vec2(14,20)))) o = pfCitadel_pal[2];
    if((((((pfCitadel_cross(p,vec2(14,20),vec2(18,20))!=pfCitadel_cross(p,vec2(18,20),vec2(18,20)))!=pfCitadel_cross(p,vec2(18,20),vec2(18,20)))!=pfCitadel_cross(p,vec2(18,20),vec2(14,20)))!=pfCitadel_cross(p,vec2(14,20),vec2(12,20)))!=pfCitadel_cross(p,vec2(12,20),vec2(14,20)))) o = pfCitadel_pal[4];
    if(pfCitadel_seg(p, vec2(12,20), vec2(18,20), 0.5)) o = pfCitadel_pal[6];
    if(pfCitadel_seg(p, vec2(14,20), vec2(18,20), 0.5)) o = pfCitadel_pal[1];
    if(pfCitadel_seg(p, vec2(14,20), vec2(16,20), 0.5)) o = pfCitadel_pal[7];
    if((p.x>=13.5 && p.x<=18.5 && p.y>=19.5 && p.y<=20.5)) o = pfCitadel_pal[1];
    if((p.x>=15.5 && p.x<=18.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[2];
    if((p.x>=15.5 && p.x<=18.5 && p.y>=15.5 && p.y<=16.5)) o = pfCitadel_pal[5];
    if((p.x>=17.5 && p.x<=18.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[2];
    if((p.x>=17.5 && p.x<=18.5 && p.y>=11.5 && p.y<=12.5)) o = pfCitadel_pal[5];
    return o;
}
void mainImage(out vec4 fragColor, in vec2 fragCoord){
    float pp=4.0;
    vec2 origin=vec2(iResolution.x*0.5-32.0*pp, iResolution.y*0.5-24.0*pp);
    vec2 sp=floor((fragCoord-origin)/pp)+0.5;
    if(iTime>1e9 || iBrightness>1e9) sp=vec2(-999.0);
    vec3 c=pfCitadel(sp, vec2(1.0,1.0));
    float a=clamp(max(max(c.r,c.g),c.b)*255.0,0.0,1.0);
    fragColor=vec4(mix(vec3(8.0,10.0,16.0)/255.0,c,a),1.0);
}
